---
apiVersion: v1
kind: Namespace
metadata:
  name: rig-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rig
  namespace: rig-system
spec:
  interval: 24h
  url: https://charts.rig.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rig-operator
  namespace: rig-system
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 30m
  chart:
    spec:
      chart: rig-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rig
        namespace: rig-system
      interval: 12h
  values:
    config:
      certManager:
        clusterIssuer: rig-issuer
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rig-platform
  namespace: rig-system
spec:
  dependsOn:
    - name: rig-operator
      namespace: rig-system
  interval: 30m
  chart:
    spec:
      chart: rig-platform
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rig
        namespace: rig-system
      interval: 12h
  values:
    postgres:
      enabled: true
