apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patch-rig-operator.yaml
  - path: patch-rig-platform.yaml

  # Uncomment to enable ingress on rig-platform
  #- path: patch-rig-platform-ingress.yaml
